# Autostart apps
exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &

exec-once=waybar
exec-once=flameshot
exec-once=solaar
exec-once=input-remapper-gtk
exec-once=gnome-disks


# Scripts
exec-once= ~/.config/mango/scripts/wallpaper-rotate.sh ~/Wallpapers/

# Reloading scripts
# exec= MyScript
