# Autostart apps
exec-once=/usr/lib/xdg-desktop-portal-wlr &
exec-once=waybar

# exec-once=/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# exec-once=wl-clip-persist --clipboard regular --reconnect-tries 0 &

# Scripts
exec-once= ~/.config/scripts/mango/wallpaper-rotate.sh ~/Wallpapers/

# Reloading scripts
# exec= MyScript
