# Config files
# Order matters

# Other (Optional)
source-optional= ./misc.conf
# Input and output devices
source= ./IO.conf
# Keybinds
source= ./bind.conf
# Theme
source= ./theme.conf
# Layout settings
source= ./layout.conf
# Autostart
source= ./autostart.conf

