# keyboard
repeat_rate=25
repeat_delay=600
numlockon=0
xkb_rules_layout=us

# Trackpad
# need relogin to make it apply
disable_trackpad=0
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0
swipe_min_threshold=1

# mouse
# need relogin to make it apply
mouse_natural_scrolling=0
mouse_accel_profile=0

# Monitor
# monitorrule=name:^DP-1$,width:2560,height:1440,refresh:160,x:1080,y:0,vrr:0
# monitorrule=name:^HDMI-A-5$,width:1920,height:1080,refresh:60,x:0,y:0,vrr:0,rr:1

allow_tearing=1

#Window rules
#windowrule=isfloating:1,appid:atlauncher
#windowrule=focused_opacity:1.0,appid:firedragon
#windowrule=focused_opacity:1.0,appid:mpv
#windowrule=focused_opacity:1.0,appid:equibop
#windowrule=focused_opacity:1.0,appid:darktable
#windowrule=focused_opacity:1.0,appid:rawtherapee
#windowrule=focused_opacity:1.0,appid:obs
#windowrule=focused_opacity:1.0,appid:XnView

# layer rule
layerrule=noshadow:1,noblur:1,layer_name:rofi
